server:
  port: 8081
  servlet:
    context-path: /EAD_6
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/UserDataBase
    username: root
    password: abcd
    driver-class-name : com.mysql.cj.jdbc.Driver
  mvc:
   view:
    prefix: /WEB-INF/pages/
    suffix: .jsp